spring.application.name=novamart-backend

spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

app.jwt.secret=5517e5f8944969b8e3f5a02b246e673cb396e64d388d05012c17efb044c9a61c
app.jwt.expiration=3600000

spring.security.user.name=user
spring.security.user.password=123456
spring.security.user.roles=USER
